### PR TITLE
cleanup UI

### PR DESCRIPTION
**Pull request by wkpark**
* [x] activate checkbox added
 * [x] fix for more consistent ui

image

image

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
I dig the checkbox+accordion all-in-one, but the second copy of the checkbox should ideally not be visible

**Comment by wkpark** [comment]
image

**Comment by mcmonkey4eva** [comment]
Might I encourage similar PRs to other relevant extensions? Especially ControlNet - the controlnet extension having a little toggle checkbox somewhere inside the accordion is so easy to miss.

**Comment by wkpark** [comment]
> Might I encourage similar PRs to other relevant extensions? Especially ControlNet - the controlnet extension having a little toggle checkbox somewhere inside the accordion is so easy to miss.

sure ^^. thanks for your great project!

**Pull request merged**
